drop table contacto if exists;
drop table reporte if exists;

create table contacto (
    id integer not null,
    apellido varchar(255),
    ciudad varchar(255),
    codigo_postal varchar(255),
    domicilio varchar(255),
    estado varchar(255),
    pais varchar(255),
    email varchar(255),
    movil varchar(255),
    nacimiento date,
    nombre varchar(255),
    telefono varchar(255),
    primary key (id));

create table reporte (
    id integer generated by default as identity,
    descripcion varchar(255),
    nombre varchar(255),
    sql clob,
    primary key (id));
